name: "Create tag"

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Commit tag
        run: |
          git tag --delete test || true
          git push --delete origin refs/tags/test || true
          git tag test main -m "Deployment status of TEST"
          git push origin refs/tags/test
